### PR TITLE
Correct Host header is not passed

### PR DESCRIPTION
**Pull request by martensson**
Hi There!
I am using oxy for my reverse proxy for Marathon Mesos (https://github.com/martensson/moxy) but I noticed that the clients Host header is never passed by oxy in the request to the servers behind.
I send you a simple PR that should fix this odd behavior :)

Best regards,
Benjamin

### CODE REVIEW

**Comment by klizhentas** [comment]
I generally agree that this is necessary, but I'm afraid it will break some components that rely on the other behavior. Can you please add a flag similar to:


```
func PassHostHeader(bool) optSetter {
	return func(f *Forwarder) error {
		f.passHost = true
		return nil
	}
}
```

and use this flag to set the behavior? Then I will be glad to merge. Thanks!

**Comment by martensson** [comment]
@klizhentas thanks for the input and it is fine with me to use the optsetter way instead. 
PR is now changed and it should not break anything anymore. :)

**Comment by klizhentas** [comment]
@martensson compared to your original PR here:

https://github.com/martensson/oxy/commit/886a7581627c1d2dc901cac20fd948f62b91c4f6

The logic has changed - in the oginal PR you were setting Host header from the request, in the latest version you are skipping this logic. Is that intentional?

**Comment by martensson** [comment]
Yes it was intentional, I noticed later that the Host header is actually already copied from the client request here: https://github.com/mailgun/oxy/blob/master/forward/fwd.go#L117

So it is actually not necessary to set `outReq.Host` again :)

Thanks for the quick answer btw!

**Comment by klizhentas** [comment]
@martensson ok, one last thing - can you please squash all commits and then I'll merge right away

**Comment by martensson** [comment]
@klizhentas done!

**Comment by klizhentas** [comment]
thanks!

**Pull request merged**
