### PR TITLE
Allow response manipulation from forwarder

### PR DESCRIPTION
**Pull request by plalloni**
This little modification introduces the ability to modify what's written to the original requestor, default implementation just copies the original response (maintaining previous behavior), but now forwarder can transform the response arbitrarily:

```go
type HelloResponder struct {}
func (h *HelloResponder) Process(w http.ResponseWriter, r *http.Response) error {
  // do some possible transformation over r and write results to w (including headers first)
  // NOTE: must update w.Header to reflect changes made
  // e.g.:
  result, length := do some transformation over r
  w.Header().Set("Content-Length", length)
  w.WriteHeader(r.StatusCode)
  io.Copy(w, result)
  return nil
}
f, _ := forward.New(forward.Processor(&HelloResponder{}))
// ...
router.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
  req.URL = "..."
  f.ServeHTTP(w, req)
})
```

### CODE REVIEW

**Comment by plalloni** [comment]
Hey, ¿has anybody had the chance to take a look at this?

**Comment by klizhentas** [comment]
@plalloni I wonder why not just wrap the middleware into another middleware using proxy writer:

https://github.com/mailgun/oxy/blob/master/utils/netutils.go#L12

```
func (h *HelloResponder) ServeHTTP(w, http.ResponseWriter, r *http.Response)  {
        pw := &utils.ProxyWriter{}
        fwd.ServeHTTP(pw, r)
        // change response captured in proxy writer
        ....
        io.Copy(r, pw.Body)
}
```

**Comment by plalloni** [comment]
Which ResponseWriter should be used for initializing ProxyWriter?
How exactly does ProxyWriter buffers/captures the output?
Where is that "Body" member of ProxyWriter declared?
Can I make ProxyWriter buffer to disk?

**Comment by klizhentas** [comment]
here's an example of how can you do this with BufferWriter:

https://github.com/mailgun/oxy/blob/master/utils/netutils.go#L52

```go
import (
    "github.com/mailgun/oxy/utils"
    "github.com/mailgun/multibuf"
)


func (h *HelloResponder) ServeHTTP(w, http.ResponseWriter, r *http.Response)  {
    // We create a special writer that will limit the response size, 
    // buffer it to disk if necessary
    writer, err := multibuf.NewWriterOnce(multibuf.MaxBytes(maxResponseBodyBytes),  
        multibuf.MemBytes(memResponseBodyBytes))

    bw := utils.NewBufferWriter(writer)
    fwd.ServeHTTP(bw, r)


    // bw has captured response code, and writer cow contains the saved response
    bw.Reader() // <--- get access to the contents of the response 
    bw.Headers()  // headers
    // now you can alter anything and then stream it back to real ResponseWriter
    io.Copy(w, bw.Reader())
     w.Header(bw.Header())
}
```

**Comment by klizhentas** [comment]
ok, closing. Let me know if you have any other questions

**Comment by braoru** [comment]
Hello, is this answer still realistic ? Or there is another option to modify the response body ?

**Comment by lalloni** [comment]
We are still using my patch on production under heavy load, so that works pretty well.
I've briefly implemented & tested @klizhentas proposal which seemed to work fine but we didn't want to switch a well tested and working implementation.

**Comment by braoru** [comment]
Ok, that a good new ! Currently I still have trouble to implement @klizhentas proposal.  I think I have some difficulties to understand the change of "WriteOnce" on the Reader() call. But I'm still new with oxy and the http framework of go and I would be grateful i you could past a simple gist with it when you find time :-).

Currently I still playing with delve (and trying to improve my understanding) and a very simple simple implementation (this version work but not with buffer https://gist.github.com/braoru/0e44575009cff3d06f2cfae547c26bb8). I would like to replace recorder with a cleaner buffer manipulation :-)

**Comment by braoru** [comment]
or a little example somewhere to start with ? :-)

**Comment by lalloni** [comment]
Ok... here https://gist.github.com/lalloni/0ccbb97adb8ef68f4627bbedaf0a1419 I've put together a quick contrived example extracted from our working code.

Note that I removed a lot of things to make it as simple as possible.

**Comment by braoru** [comment]
@lalloni thank a lot ! I begin to understand why my sample was not working and I still have a lot to learn on how net/http is working internally ! :-)

**Pull request closed without merging**
